AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-product-app

  Sample SAM Template for simple-product-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ProductDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProductTable
      AttributeDefinitions:
        - AttributeName: ProductId
          AttributeType: S
  
      KeySchema:
        - AttributeName: ProductId
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ProductAppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductDynamoDBTable
        - S3ReadPolicy:
            BucketName: !Ref ProductImageBucket
        - S3WritePolicy:
            BucketName: !Ref ProductImageBucket

      CodeUri: product-app/
      Handler: index.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
      - x86_64
      Events:
       CreateProductEvent:
          Type: Api
          Properties:
            Path: /product
            Method: POST

       GetProductsEvent:
          Type: Api
          Properties:
            Path: /products
            Method: GET
       DeleteProductEvent:
          Type: Api
          Properties:
            Path: /product/{productId}
            Method: DELETE

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - index.ts

  ProductImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-product-image-bucket
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3UploadEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event rule to trigger Lambda on S3 uploads
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - ObjectCreated:Put
        resources:
          - !GetAtt ProductImageBucket.Arn
      Targets:
        - Arn: !GetAtt ProductAppFunction.Arn
          Id: S3UploadLambdaTarget


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProductAppApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ProductAppFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt ProductAppFunction.Arn
  ProductAppFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ProductAppFunctionRole.Arn
  ProductDynamoDBTable:
    Description: DynamoDB Table for storing products
    Value: !Ref ProductDynamoDBTable
  ProductImageBucketName:
    Description: Name of the product image bucket
    Value: !Ref ProductImageBucket
  S3UploadEventRuleArn:
    Description: ARN of the S3 upload EventBridge rule
    Value: !Ref S3UploadEventRule