AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for simple-product-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

Resources:
  ProductDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProductTable
      AttributeDefinitions:
        - AttributeName: ProductId
          AttributeType: S

      KeySchema:
        - AttributeName: ProductId
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ImageProcessingLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: image-processing-layer
      Description: Layer for sharp dependency
      ContentUri: ./dependencies
      CompatibleRuntimes:
        - nodejs18.x

  ProductAppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductDynamoDBTable
        - S3ReadPolicy:
            BucketName: !Ref ProductImageBucket
        - S3WritePolicy:
            BucketName: !Ref ProductImageBucket
        - S3WritePolicy:
            BucketName: !Ref ProductOptimizedImageBucket

      Layers:
        - !Ref ImageProcessingLayer
      CodeUri: product-service/
      Handler: index.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        CreateProductEvent:
          Type: Api
          Properties:
            Path: /product
            Method: POST

        GetProductsEvent:
          Type: Api
          Properties:
            Path: /products
            Method: GET
        DeleteProductEvent:
          Type: Api
          Properties:
            Path: /product/{productId}
            Method: DELETE
        UploadProductEvent:
          Type: Api
          Properties:
            Path: /product/upload
            Method: POST

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - index.ts
        External:
          - "sharp"

  ProductImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 20230820-product-image-bucket
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ProductOptimizedImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 20230820-product-optimized-image-bucket
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  S3UploadEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event rule to trigger Lambda on S3 uploads
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref ProductImageBucket 
      Targets:
        - Arn: !GetAtt ProductAppFunction.Arn
          Id: S3UploadLambdaTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProductAppFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3UploadEventRule.Arn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
  
Outputs:
  CreateProductApi:
    Description: "Create API endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product"

  GetProductsApi:
    Description: "Get API endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products"

  DeleteProductApi:
    Description: "Delete API endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product/{productId}"

  UploadProductApi:
    Description: "Upload API endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product/upload"

  ProductAppFunction:
    Description: Product App Function ARN
    Value: !GetAtt ProductAppFunction.Arn

  ProductDynamoDBTable:
    Description: DynamoDB Table for storing products
    Value: !Ref ProductDynamoDBTable

  ProductImageBucketName:
    Description: Name of the product image bucket
    Value: !Ref ProductImageBucket

  S3UploadEventRuleArn:
    Description: ARN of the S3 upload EventBridge rule
    Value: !Ref S3UploadEventRule
